spring:
  ai:
    ollama:
      api-key: jack
      base-url: http://localhost:11434/
      chat:
        options:
          model: qwen3:1.7b
      embedding:
        model: nomic-embed-text
    mcp:
      client:
        enabled: true
        name: mcp-client
        version: 1.0
        type: SYNC
        request-timeout: 60s
        stdio:
          servers-configuration: classpath:/mcp-server-settings.json
        sse:
          connections:
            webmvc-mcp-server:
              url: http://localhost:8081
              sse-endpoint: /sse

